[versions]
kotlin = "2.1.10"

dokka = "1.9.20"
mavenPublish = "0.30.0"

kotlinx-binaryCompatibilityValidator = "0.17.0"

kotlinx-coroutines = "1.10.1"

okio = "3.10.2"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

kotlinx-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibilityValidator" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-nodeFilesystem = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }
okio-fakeFilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
